test_that("Test endpoints", {
  expect_type(get_endpoint("googledrive.endpoint"), "character")
  expect_type(get_endpoint("classroom.endpoint.user"), "character")
  expect_type(get_endpoint("classroom.endpoint.course.get"), "character")
  expect_type(get_endpoint("classroom.endpoint.course", "made_up_course_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.topic.get", "made_up_course_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.topic", "made_up_course_id", topic_id = "made_up_topic_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.coursework.get", "made_up_course_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.coursework", "made_up_course_id", coursework_id = "made_up_coursework_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.materials.get", "made_up_course_id"), "character")
  expect_type(get_endpoint("classroom.endpoint.materials", "made_up_course_id", materials_id = "made_up_materials_id"), "character")
  expect_type(get_endpoint("forms.endpoint.get"), "character")
  expect_type(get_endpoint("forms.endpoint", form_id = "made_up_form_id"), "character")
  expect_type(get_endpoint("forms.endpoint.batchUpdate", form_id = "made_up_form_id"), "character")
})
