
##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: no
# Check that urls in the content are not broken
url-checker: yes
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
# Spell check Rmds and quizzes
spell-check: yes
# Style any R code
style-code: yes
# Test build the docker image if any docker-relevant files have been changed
docker-test: no
# Do we need to make the book txt file automatically? 
make_book_txt: yes

##### Renderings run upon merge to main branch #####
# Rendering each platform's content
render-website: quarto
render-leanpub: yes
render-coursera: no

# What docker image should be used for rendering?
# The default is jhudsl/base_ottr:latest
rendering-docker-image: 'jhudsl/base_ottr:latest'

